### PR TITLE
Fix: Pass validation for non-normalized evm

### LINKED ISSUE #241: Send flow. EVM. Non-normalized EVM address counts as wrong
**Env:**
Release v1.4.0

When user put non-normalized address in send flow it will count as wrong address and block the flow:

**Non-Normalized:**
0x4c2ab98b646ce36df6a4a4407ab9fcee1c90549a

**Normalized:**
0x1A9E615529BE125603759a754a47dfcB38453D32

Example:
Screenshot 2024-10-18 at 18 31 42

Screenshot 2024-10-18 at 18 32 18

### PR DESCRIPTION
**Pull request by tuul-wq**
- Removed checksum validation for evm address
- Added decimal keyboard of `<AmountInput />` for mobile devices
- Removed default `0` value for Amount step, so user can enter value not just staring from `0`

closes #241 

image

### CODE REVIEW

File: app/root.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ export const loader = (() => {
   });
 }) satisfies LoaderFunction;
 
-const DataContext = ({ children }: PropsWithChildren) => {
```
Comment (tuul-wq) [inline app/root.tsx:72]: Caused some weird error for `useLoaderData` being `undefined` ([answer](https://github.com/remix-run/remix/discussions/9681))

File: app/ui/atoms/Inputs/AmountInput.tsx [hunk 2]
```diff
@@ -26,14 +26,15 @@ export const AmountInput = ({ value, placeholder = '0.00', isValid, className, o
...
+      inputMode="decimal"
       mask={Number}
       min={0}
       scale={15}
       value={value}
       radix="."
       mapToRadix={[',']}
       autofix={true}
-      normalizeZeros={false}
+      normalizeZeros={true}
```
Comment (tuul-wq) [inline app/ui/atoms/Inputs/AmountInput.tsx:37]: Converts `000.250` to this `0.25` on blur

**Review by johnthecat — APPROVED** [review]
