### PR TITLE
Fix: Bad assets

### LINKED ISSUE #227: Android. Wrong behaviour with asset management.
When user change assets on manage tokens and reload the app - may lead to broken state on main page.

Example:

https://github.com/user-attachments/assets/e2567cfb-8ddc-452d-829b-a06f55c97df8

**Case:**
1. Load Telenova on android
2. Change active assets on Manage tokens
3. Reload the page

**Expected result:**
Always shows dot\ksm\usdt and selected assets on manage tokens

**Actual result:**
KSM and USDT may disappear from the list

**Environment:**
Android
dev - https://github.com/novasamatech/telenova-web-app/commit/a34e94df1f4ec50628351254ebdf56ca4e02d1a9

Does not reproduce on the PROD

### PR DESCRIPTION
**Pull request by tuul-wq**
- Handle wrong assets from Cloud Storage (Looks like some bad `assetId` crawled into our TG storage during stage testing for me and Stepan)
- Tests

closes #227

### CODE REVIEW

File: app/models/network/network-model.ts [hunk 1]
```diff
@@ -215,22 +219,24 @@ sample({
...
 
+// Init connections for DEFAULT_CONNECTED_CHAINS (dot, ksm, usdt)
 sample({
   clock: requestChainsFx.doneData,
   fn: chains => {
     const chainsMap: Record<ChainId, AssetId[]> = {};
 
-    for (const chain of Object.values(chains)) {
-      if (!DEFAULT_CONNECTED_CHAINS[chain.chainId]) continue;
+    for (const [chainId, assets] of Object.entries(DEFAULT_CONNECTED_CHAINS)) {
```
Comment (tuul-wq) [inline app/models/network/network-model.ts:228]: `DEFAULT_CONNECTED_CHAINS` has much less elements than `chains`

File: app/models/network/network-model.ts [hunk 2]
```diff
@@ -171,13 +173,15 @@ const $sortedAssets = combine($assets, assets => {
...
+      if (!asset) continue;
+
+      if (!chainToPresort || !(asset.assetId in chainToPresort)) {
         assetsToSort.push([typedChainId, asset]);
       } else {
-        const index = DEFAULT_CHAINS_ORDER[typedChainId][asset.assetId];
+        const index = chainToPresort[asset.assetId];
         preSortedAssets[index] = [typedChainId, asset];
       }
     }
```
Comment (johnthecat) [inline app/models/network/network-model.ts]: Looks like if statement is turned inside out. 
```ts
for (const asset of Object.values(assetMap)) {
  if (!asset) continue;

  if (chainToPresort && (asset.assetId in chainToPresort)) {
    const index = chainToPresort[asset.assetId];
    preSortedAssets[index] = [typedChainId, asset];
  } else {
    assetsToSort.push([typedChainId, asset]);
  }
}
```

**Review by johnthecat — APPROVED** [review]
